#!/usr/bin/env node

// validate -- validate the given YAML document from stdin against the given schema
// usage: validate [<schema-file>] < yaml

'use strict';

const yaml = require('yaml');
const stdin = require('./lib/stdin');
const validatorAjv = require('./lib/validator-ajv');

async function main() {
  const schemaFile = process.argv[2] || `${__dirname}/../schemas/v1.0/schema.yaml`;
  const validator = validatorAjv.create(schemaFile);

  const document = yaml.parse(stdin.readAllSync());
  const result = await validator.validate(document);

  if (!result.valid) {
    result.errors.forEach(error => {
      console.log(`error: ${error.message} at ${error.instancePath}`);
    });
  }
  process.exitCode = result.valid ? 0 : 1;
}

(async () => {
  try {
    await main();
  } catch (e) {
    console.error(`error: ${e.message}`);
    process.exitCode = 2;
  }
})();
